openapi: 3.0.0
info:
  title: AI Spine API
  version: 1.0.0
  description: Multi-agent orchestration infrastructure for coordinated AI workflows
  contact:
    name: AI Spine Team
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://production-domain.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy

  /:
    get:
      summary: Root endpoint
      description: Returns basic API information
      operationId: getRoot
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: AI Spine API
                  version:
                    type: string
                    example: 1.0.0
                  docs:
                    type: string
                    example: /docs

components:
  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message